DEBUG = True
UDP_PORT = 9001
UDP_HOST = '127.0.0.1'

REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379

REDIS_KEYS_PREFIX = 'statistics'
FIELDS = ['CPU', 'TOTAL', 'SQL', 'SOLR', 'REDIS', 'MEMCACHED', 'REQUESTS']
